services:
  db:
    image: postgres
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: reminderApp
      POSTGRES_USER: keti
      POSTGRES_PASSWORD: cKiJ3tX3@hA2