services:
  postgres:
    image: postgres
    container_name: reminders-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: reminderApp
      POSTGRES_USER: keti
      POSTGRES_PASSWORD: cKiJ3tX3@hA2